// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbRWp9jbLMLtXHtAsq9nZeURtqtNbLfKE',
    appId: '1:633055788834:web:e8d08edf620ae0514eaf7b',
    messagingSenderId: '633055788834',
    projectId: 'civilsgpt-659cd',
    authDomain: 'civilsgpt-659cd.firebaseapp.com',
    storageBucket: 'civilsgpt-659cd.appspot.com',
    measurementId: 'G-HPYL4QXGJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDopK3WjHc2MftAS7285rLl74-OI08roY4',
    appId: '1:632264443335:android:c186974f85b23b5fe805e2',
    messagingSenderId: '632264443335',
    projectId: 'civilsgpt',
    storageBucket: 'civilsgpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvYIVrx0kNrulaaY2qZDFqwzi81IASiU',
    appId: '1:632264443335:ios:446afb35b56994d5e805e2',
    messagingSenderId: '632264443335',
    projectId: 'civilsgpt',
    storageBucket: 'civilsgpt.appspot.com',
    iosClientId: '632264443335-0heu7j7t4b9d7fp9t93519u8insthp49.apps.googleusercontent.com',
    iosBundleId: 'org.civils.gpt.civilsGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnp7Wu8h3Kb1OvlZkwg9VpE2-yZVbDeA',
    appId: '1:633055788834:ios:793ed5dc66490fca4eaf7b',
    messagingSenderId: '633055788834',
    projectId: 'civilsgpt-659cd',
    storageBucket: 'civilsgpt-659cd.appspot.com',
    iosBundleId: 'com.civils.gpt.civilsGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbRWp9jbLMLtXHtAsq9nZeURtqtNbLfKE',
    appId: '1:633055788834:web:53ed49682da9b08a4eaf7b',
    messagingSenderId: '633055788834',
    projectId: 'civilsgpt-659cd',
    authDomain: 'civilsgpt-659cd.firebaseapp.com',
    storageBucket: 'civilsgpt-659cd.appspot.com',
    measurementId: 'G-BYVKGP3BQ3',
  );

}